### ISSUE TITLE
Debug HW for messuring electronics

### ISSUE THREAD

**Issue by BigGold1310** [coderbunker/energy-monitor#8]
FIX the wrong power consumption measurement

- [x] Circuit analysis of electronic construction
- [x] Redimension hardware to get stable, useable signal on Measurement-Resistor
- [x] Comission ADC+Eval Board: System measures Current consumption correct.
- [x] Test hardware on air conditioner
- [x] Finish Documentation on Debugging Hardware

**Comment by joelvonrotz** [comment]
- [x] Measure voltage on measurement-reistor
- [x] Calculate ratio out of measured voltage & current and calculated voltage & current
- [ ] Test hardware on air conditioner

**Comment by joelvonrotz** [comment]
- [x] Measure voltage on measurement-reistor
- [x] Calculate ratio out of measured voltage & current and calculated voltage & current
- [ ] Test hardware on air conditioner

**Comment by codebru** [comment]
@joelvonrotz @BigGold1310 by the comments I assume this is done and will close.
